name: dotnetcore-webapp-ci-cd-argocd

on:
  #push:
  #  branches:
  #    - feature/*
  #    - release/*
  #    - develop
  #pull_request:
  #  branches:
  #    - develop
  #    - main
  workflow_dispatch: 

env:
  CONFIGURATION: Release
  
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR Login
        run: az acr login --name ${{ vars.ACR_URL }}
      
      - name: Build and push WebApi image
        uses: docker/build-push-action@v3
        with:
          context: src/MyFirstProject.WebApi
          file: src/MyFirstProject.WebApi/Dockerfile
          tags: |
            ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}
            ${{ vars.ACR_URL }}/myfirstproject.webapi:latest
          push: true

      - name: Build and push WebApp image
        uses: docker/build-push-action@v3
        with:
          context: src/MyFirstProject.WebApp
          file: src/MyFirstProject.WebApp/Dockerfile
          tags: |
            ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}
            ${{ vars.ACR_URL }}/myfirstproject.webapp:latest
          push: true
      
      - name: View images
        run: docker images
  
  modify-config-files:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
        name: Checkout config repository
        with:
          repository: 'prado-org/dotnetcore-webapp-config'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      
      - name: Modify deployment files
        run: |
          git config user.email actions@github.com
          git config user.name "GitHub Actions"
          pwd
          cat WebApi/k8s-deployment.yaml
          pwd
          sed -i "s/acrdotnetproject.azurecr.io\/myfirstproject.webapi:latest/acrdotnetproject.azurecr.io\/myfirstproject.webapi:$RUN_NUMBER/" k8s-deployment.yaml
          cat WebApi/k8s-deployment.yaml
          git add .
          git commit -m 'Done by Github Actions Job changemanifest: $RUN_NUMBER'
          git push origin main
        env:
          RUN_NUMBER: ${{ GITHUB.RUN_NUMBER }}