name: dotnetcore-webapp-ci-cd-docker

on:
  #push:
  #  branches:
  #    - feature/*
  #    - release/*
  #    - develop
  #pull_request:
  #  branches:
  #    - develop
  #    - main
  workflow_dispatch: 

env:
  CONFIGURATION: Release
  
jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
     
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: ACR Login
      run: az acr login --name ${{ vars.ACR_URL }}
    
    - name: Build and push WebApi image
      uses: docker/build-push-action@v3
      with:
        context: src/MyFirstProject.WebApi
        file: src/MyFirstProject.WebApi/Dockerfile
        tags: |
          ${{ vars.ACR_URL }}/myfirstproject.webapi:${{ GITHUB.RUN_NUMBER }}
          ${{ vars.ACR_URL }}/myfirstproject.webapi:latest
        push: true

    - name: Build and push WebApp image
      uses: docker/build-push-action@v3
      with:
        context: src/MyFirstProject.WebApp
        file: src/MyFirstProject.WebApp/Dockerfile
        tags: |
          ${{ vars.ACR_URL }}/myfirstproject.webapp:${{ GITHUB.RUN_NUMBER }}
          ${{ vars.ACR_URL }}/myfirstproject.webapp:latest
        push: true
    
    - name: View images
      run: docker images
    
    - name: Upload Kubernetes files
      uses: actions/upload-artifact@v3.0.0
      with:
        name: k8s
        path: |
          src/MyFirstProject.WebApi/k8s-deployment.yaml
          src/MyFirstProject.WebApp/k8s-deployment.yaml
