name: pipeline-reusable

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  reusable-build-workflow:
    uses: prado-org/reusable-workflows/.github/workflows/example.yml@main
    with:
      msg: 'Teste Leandro Prado'
      runner-name: 'ubuntu-latest'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.