name: pipeline-reusable

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  example-workflow:
    uses: prado-org/reusable-workflows/.github/workflows/example.yml@main
    with:
      msg: 'Teste Leandro Prado'
      runner-name: 'ubuntu-latest'
  
  dotnet-build:
    uses: prado-org/reusable-workflows/.github/workflows/build-dotnet-core.yml@main
    with:
      configuration: 'Release'
      path-csproj: 'src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj'
      runner-name: 'ubuntu-latest'
  
  deploy-azure-webapp-dev:
    uses: prado-org/reusable-workflows/.github/workflows/deploy-azure-webapp.yml@main
    needs: dotnet-build
    with:
      runner-name: 'ubuntu-latest'
      webapp-name: 'app-MyFirstProject-dev'
      environment-name: 'webapp-dev'
    secrets: inherit
  
  deploy-azure-webapp-hml:
    uses: prado-org/reusable-workflows/.github/workflows/deploy-azure-webapp.yml@main
    needs: deploy-azure-webapp-dev
    with:
      runner-name: 'ubuntu-latest'
      webapp-name: 'app-MyFirstProject-hml'
      environment-name: 'webapp-hml'
    secrets: inherit
  
  deploy-azure-webapp-prd:
    uses: prado-org/reusable-workflows/.github/workflows/deploy-azure-webapp.yml@main
    needs: deploy-azure-webapp-hml
    with:
      runner-name: 'ubuntu-latest'
      webapp-name: 'app-MyFirstProject-prd'
      environment-name: 'webapp-prd'
    secrets: inherit
