name: pipeline-reusable

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  reusable-example-workflow:
    uses: prado-org/reusable-workflows/.github/workflows/example.yml@main
    with:
      msg: 'Teste Leandro Prado'
      runner-name: 'ubuntu-latest'
  
  reusable-dotnet-build:
    uses: prado-org/reusable-workflows/.github/workflows/build-dotnet-core.yml@main
    with:
      configuration: 'Release'
      path-csproj: 'src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj'
      runner-name: 'ubuntu-latest'
  
  reusable-deploy-azure-webapp:
    uses: prado-org/reusable-workflows/.github/workflows/deploy-azure-webapp.yml@main
    needs: reusable-dotnet-build
    with:
      runner-name: 'ubuntu-latest'
      webapp-name: 'my-first-project-webapp'
    secrets: inherit
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.