name: run-start-workflow

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  start-workflow:
    uses: prado-org/reusable-workflows/.github/workflows/start-dotnet.yml@main
    with:
      runner-name: 'ubuntu-latest'
      path-csproj: 'src/MyFirstProject.WebApp/MyFirstProject.WebApp.csproj'