name: test-variables

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Secrets
        run: |
          echo Secrets
          echo ${{ secrets.REPO_MY_SECRET }}
          echo ${{ secrets.ORG_MY_SECRET }}
           
      - name: Variables
        run: |
          echo Variables
          echo ${{ vars.REPO_MY_VARIABLE }}
          echo ${{ vars.ORG_MY_VARIABLE }}
