name: test-variables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Secrets
        run: |
          echo Secrets
          echo $REPO_MY_SECRET
          echo $ORG_MY_SECRET
      - name: Variables
        run: |
          echo Variables
          echo $REPO_MY_VARIABLE
          echo $ORG_MY_VARIABLE
